server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:./meta.db
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema.sql
  jackson:
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as_strings: true
    default-property-inclusion: non_empty


logging:
  level:
    org:
      apache:
        ibatis: DEBUG
      springframework:
        transaction: DEBUG